server:
  port: 8005

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.124.1:3306/x5?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  application:
      name: staff-consumer
  profiles: dev


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: staff-consumer-${server.port}
    prefer-ip-address: true







