server:
  port: 9902


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
    application:
      name: gitway_wg
    profiles: dev
    redis:
      host: 192.168.124.178
      port: 6380
    cloud:
      gateway:
        routes:
          - id: STAFF-CONSUMER
            uri: lb://STAFF-CONSUMER
            predicates:
              - Path=/con/**
            filters:
              - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: debug